build:
	gcc -Wall -Wextra ninel.c -o ninel
	gcc -Wall -Wextra vectsecv.c -o vectsecv
	gcc -Wall -Wextra codeinvim.c -o codeinvim
	gcc -Wall -Wextra nomogram.c -o nomogram

run:
	./ninel
	./vectsecv
	./codeinvim
	./nomogram

clean:
	rm -f ninel
	rm -f vectsecv
	rm -f codeinvim
	rm -f nomogram

.PHONY: clean